# Generated by Django 4.0.4 on 2022-05-14 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amenities_Type', models.CharField(max_length=20)),
                ('Amenities_Location', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('Direct_or_Guarantor', models.CharField(max_length=1)),
                ('Lease_ID', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('Renter_ID', models.CharField(max_length=7)),
                ('Rent_Amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Lease_Type', models.CharField(choices=[('Lease Application', 'Application'), ('Active Lease', 'Active Lease')], default='Active Lease', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance_Request',
            fields=[
                ('Issue', models.CharField(max_length=30)),
                ('Work_Order_ID', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('Unit_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('License_Plate', models.CharField(max_length=8)),
                ('Parking_Permit_ID', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('Person_Name', models.CharField(max_length=22)),
                ('SSN', models.IntegerField(unique=True)),
                ('Permanent_Address', models.CharField(max_length=30)),
                ('ID', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('Person_Type', models.CharField(choices=[('Tenant', 'Tenant'), ('Staff', 'Staff')], default='Tenant', max_length=6)),
            ],
            options={
                'ordering': ['Person_Name'],
            },
        ),
        migrations.CreateModel(
            name='Rent_Payment',
            fields=[
                ('Amount_Paid', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Payment_ID', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('Unit_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lease_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.lease')),
                ('Parking_Permit_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.parking')),
                ('Renter_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.person')),
                ('Unit_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.unit')),
                ('Work_Order_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.maintenance_request')),
            ],
        ),
        migrations.AddField(
            model_name='parking',
            name='Govt_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.person'),
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('Inspection_ID', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('Reason', models.TextField(blank=True, max_length=255)),
                ('Building_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.building')),
                ('Performed_By', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.person')),
                ('Unit_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.unit')),
            ],
        ),
    ]
